using System;
using System.Linq;
using System.Threading.Tasks;

using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins.Cache;

using TrueUnleveledSkyrim.Config;
using TrueUnleveledSkyrim.Patch;


namespace TrueUnleveledSkyrim
{
    public class Patcher
    {
        public static readonly Random Randomizer = new();
#pragma warning disable CA2211
        public static Lazy<TUSConfig> ModSettings = null!;
#pragma warning restore CA2211

        public static ILinkCache LinkCache { get; set; } = null!;

        public static async Task<int> Main(string[] args)
        {
            args = EnsureSplitIfMaxMastersExceeded(args);

            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(nickname: "Mod Settings", path: "settings.json", out ModSettings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "TUS.esp")
                .Run(args);
        }

        // Workaround for a Synthesis GUI bug: the "Split Files if Max Masters Exceeded" profile
        // setting is not passed through as a value-bearing flag for CLI-patchers. Synthesis still
        // appends the bare flag name "--SplitIfMaxMastersExceeded" with NO trailing "true"/"false",
        // which the parser silently fails to apply (confirmed directly: this is what a real crash
        // log for this patcher showed). Because the bare flag is already present, a presence-only
        // check (as used by some other patchers with this same workaround) would wrongly treat it
        // as already handled and skip fixing it. This strips out any existing occurrence -- bare or
        // valued -- and always appends a single well-formed "--SplitIfMaxMastersExceeded true".
        private static string[] EnsureSplitIfMaxMastersExceeded(string[] args)
        {
            var newArgs = new List<string>();
            for (int i = 0; i < args.Length; i++)
            {
                if (args[i].Equals("--SplitIfMaxMastersExceeded", StringComparison.OrdinalIgnoreCase))
                {
                    if (i + 1 < args.Length &&
                        (args[i + 1].Equals("true", StringComparison.OrdinalIgnoreCase) ||
                         args[i + 1].Equals("false", StringComparison.OrdinalIgnoreCase)))
                    {
                        i++;
                    }
                    continue;
                }
                newArgs.Add(args[i]);
            }

            newArgs.Add("--SplitIfMaxMastersExceeded");
            newArgs.Add("true");
            return newArgs.ToArray();
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            LinkCache = state.LoadOrder.PriorityOrder.ToImmutableLinkCache();

            TUSConstants.GetPaths(state);
            if (ModSettings.Value.UnlevelItems)
            {
                LeveledItemsPatcher.PatchLVLI(state);
                OutfitsPatcher.PatchOutfits(state);
            }

            if (ModSettings.Value.UnlevelNPCs)
            {
                NPCsPatcher.PatchNPCs(state);
            }

            if (ModSettings.Value.UnlevelZones)
            {
                ZonesPatcher.PatchZones(state);
            }

            if (ModSettings.Value.RebalanceEquipment)
            {
                ItemsPatcher.PatchItems(state);
            }
        }
    }
}
